package club.banyuan.project.view;

import club.banyuan.project.pojo.Student;
import club.banyuan.project.util.PojoUtil;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public  class StuGetScore extends javax.swing.JFrame {
        static StuGetScore stuGetScore;


        /**
         * Creates new form StuRegister
         */
        public StuGetScore() {
            initComponents();
            setLocationRelativeTo(null);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {
            this.setTitle("学生");
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jLabel10 = new javax.swing.JLabel();
            jLabel12 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N

            jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
            jLabel1.setText("半圆学生考试系统");

            jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
            jLabel2.setText("科目");

            jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
            jLabel3.setText("分数");

            jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
            jLabel4.setText("Java");

            jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
            jLabel5.setText("Python");

            jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
            jLabel6.setText("Databases");

            jLabel7.setText(String.valueOf(PojoUtil.getStudent().getPython()));

            jLabel8.setText(String.valueOf(PojoUtil.getStudent().getJava()));

            jLabel9.setText(String.valueOf(PojoUtil.getStudent().getDatabase()));

            jButton1.setText("确定");
            jButton1.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    dispose();
                    StudentMain.startUI();
                }
            });

            jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
            jLabel10.setText("您好");


            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addGap(77, 77, 77)
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(jLabel5)
                                                                            .addComponent(jLabel6)
                                                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addGap(26, 26, 26)
                                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGap(62, 62, 62)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel7)
                                                            .addComponent(jLabel8)
                                                            .addComponent(jLabel9)
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(jLabel10))
                                                                    .addGap(18, 18, 18)
                                                                    .addComponent(jLabel12)))
                                                    .addGap(0, 18, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addComponent(jButton1)))
                                    .addGap(25, 25, 25))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                    .addComponent(jButton1)
                                    .addGap(22, 22, 22))
            );

            pack();
        }// </editor-fold>


    public static void startUI() {
            EventQueue.invokeLater(new Runnable() {
                public void run() {
                    if (stuGetScore==null){
                        synchronized (Login.class) {
                            if (stuGetScore == null) {
                                stuGetScore = new StuGetScore();
                                stuGetScore.setVisible(true);
                            }
                        }
                    }else {
                        stuGetScore.setVisible(true);
                    }
                }
            });

        }


    // Variables declaration - do not modify
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;

    }
